// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 默认侧边栏（自动生成）
  tutorialSidebar: [{type: 'autogenerated', dirName: 'intro'}],

  // Linux基础概览侧边栏
  linuxIntroSidebar: [{type: 'autogenerated', dirName: 'linux-basics/basic'}],

  // Linux命令侧边栏
  linuxCommandsSidebar: [{
    type: 'autogenerated',
    dirName: 'linux-basics/commands',
  }],
  // Linux系统管理侧边栏
    linuxSystemSidebar: [{
    type: 'autogenerated',
    dirName: 'linux-basics/system-admin',
  }],

  // 数据库专题侧边栏
    linuxdatabaseSidebar: [{
    type: 'autogenerated',
    dirName: 'linux-basics/database',
  }],
  // devops专栏侧边栏
  linuxdevopsSidebar: [{
    type: 'autogenerated',
    dirName: 'linux-basics/cicd',
  }],
  // Terraform侧边栏
  terraformSidebar: [{
    type: 'autogenerated',
    dirName: 'linux-basics/terraform',
  }],
  // 云原生概览侧边栏
  cloudNativeSidebar: [{type: 'autogenerated', dirName: 'cloud-native'}],

  // Kubernetes侧边栏
  kubernetesSidebar: [{type: 'autogenerated', dirName: 'cloud-native/kubernetes'}],

  // Prometheus侧边栏
  prometheusSidebar: [{type: 'autogenerated', dirName: 'cloud-native/prometheus'}],

  // 脚本语言概览侧边栏
  scriptingIntroSidebar: [{type: 'autogenerated', dirName: 'scripting-languages'}],

  // Python脚本侧边栏
  pythonSidebar: [{type: 'autogenerated', dirName: 'scripting-languages/python'}],

  // Shell脚本侧边栏
  shellSidebar: [{type: 'autogenerated', dirName: 'scripting-languages/shell'}],

  // 故障记录侧边栏
  troubleshootingSidebar: [{type: 'autogenerated', dirName: 'other/troubleshooting'}],

  // 工作软件侧边栏
  softwareSidebar: [{type: 'autogenerated', dirName: 'other/software'}],
};

export default sidebars;
