// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 默认侧边栏（自动生成）
  tutorialSidebar: [{type: 'autogenerated', dirName: 'intro'}],

  // Linux基础概览侧边栏
  linuxIntroSidebar: [
    'linux-basics/intro',
    // 可以继续添加更多Linux概览文档
  ],

  // Linux命令侧边栏
  linuxCommandsSidebar: [
    'linux-basics/commands',
    'linux-basics/commands/advanced',
    // 可以继续添加更多Linux命令文档
  ],

  // 云原生概览侧边栏
  cloudNativeSidebar: [
    'cloud-native/intro',
    // 可以继续添加更多云原生相关文档
  ],

  // Kubernetes侧边栏
  kubernetesSidebar: [
    'cloud-native/kubernetes/intro',
    // 可以添加更多Kubernetes相关文档
  ],

  // Prometheus侧边栏
  prometheusSidebar: [
    'cloud-native/prometheus/intro',
    // 可以添加更多Prometheus相关文档
  ],

  // 脚本语言概览侧边栏
  scriptingIntroSidebar: [
    'scripting-languages/intro',
    // 可以继续添加更多脚本语言概览文档
  ],

  // Python脚本侧边栏
  pythonSidebar: [
    'scripting-languages/python/intro',
    // 可以继续添加更多Python相关文档
  ],

  // Shell脚本侧边栏
  shellSidebar: [
    'scripting-languages/bash',
    'scripting-languages/shell/advanced',
    // 可以继续添加更多Shell相关文档
  ],

  // 故障记录侧边栏
  troubleshootingSidebar: [
    'troubleshooting/system',
    'troubleshooting/network',
    'troubleshooting/application',
  ],

  // 工作软件侧边栏
  softwareSidebar: [
    'software/development',
    'software/ops',
    'software/office',
  ],
};

export default sidebars;
